name: Sync main and latest
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set git config user
        run: git config user.email "compose-devrel-github-bot@google.com" && git config user.name "compose-devrel-github-bot"

      - name: Merge main into latest
        run: git fetch && git switch latest && git merge -s ours origin/main --allow-unrelated-histories

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: 🤖 Sync main to latest
          committer: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          author: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          signoff: false
          branch: bot-sync-main
          delete-branch: true
          title: '🤖 Sync main to latest'
          body: 'Update `latest` with `main`'
          reviewers: ${{ github.actor }}
